In [ ]:
pip install beautifulsoup4 requests lxml

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (4.13.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (2.32.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.11/dist-packages (5.4.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests) (2025.1.31)

In [ ]:
import requests

url = 'https://en.wikipedia.org/wiki/Blog'
response = requests.get(url)
html = response.content

In [ ]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(html, 'lxml')  # 'html.parser' is slower, 'lxml' is faster

In [ ]:
title_tag = soup.find('title')
print(title_tag.text)

Blog - Wikipedia

In [ ]:
all_links = soup.find_all('a')
for link in all_links:
    print(link.get('href'))

#bodyContent
/wiki/Main_Page
/wiki/Wikipedia:Contents
/wiki/Portal:Current_events
/wiki/Special:Random
/wiki/Wikipedia:About
//en.wikipedia.org/wiki/Wikipedia:Contact_us
/wiki/Help:Contents
/wiki/Help:Introduction
/wiki/Wikipedia:Community_portal
/wiki/Special:RecentChanges
/wiki/Wikipedia:File_upload_wizard
/wiki/Special:SpecialPages
/wiki/Main_Page
/wiki/Special:Search
https://donate.wikimedia.org/?wmf_source=donate&wmf_medium=sidebar&wmf_campaign=en.wikipedia.org&uselang=en
/w/index.php?title=Special:CreateAccount&returnto=Blog
/w/index.php?title=Special:UserLogin&returnto=Blog
https://donate.wikimedia.org/?wmf_source=donate&wmf_medium=sidebar&wmf_campaign=en.wikipedia.org&uselang=en
/w/index.php?title=Special:CreateAccount&returnto=Blog
/w/index.php?title=Special:UserLogin&returnto=Blog
/wiki/Help:Introduction
/wiki/Special:MyContributions
/wiki/Special:MyTalk
#
#History
#Origins
#Technology
#Rise_in_popularity
#Political_impact
#Mainstream_popularity
#Types
#Community_and_cataloging
#Early_popularity
#Software
#Blurring_with_the_mass_media
#Consumer-generated_advertising
#Legal_and_social_consequences
#Defamation_or_liability
#Employment
#Business_owners
#Political_dangers
#Personal_safety
#See_also
#References
#Further_reading
#External_links
https://af.wikipedia.org/wiki/Webjoernaal
https://ar.wikipedia.org/wiki/%D9%85%D8%AF%D9%88%D9%86%D8%A9
https://an.wikipedia.org/wiki/Blog
https://as.wikipedia.org/wiki/%E0%A6%AC%E0%A7%8D%E0%A6%B2%E0%A6%97
https://ast.wikipedia.org/wiki/Blogue
https://az.wikipedia.org/wiki/Bloq
https://bn.wikipedia.org/wiki/%E0%A6%AC%E0%A7%8D%E0%A6%B2%E0%A6%97
https://zh-min-nan.wikipedia.org/wiki/B%C4%81ng-ch%C3%AC
https://ba.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%B3
https://be.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%B3
https://be-tarask.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%B3
https://bh.wikipedia.org/wiki/%E0%A4%AC%E0%A5%8D%E0%A4%B2%E0%A5%89%E0%A4%97
https://bg.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%B3
https://bar.wikipedia.org/wiki/Blog
https://bs.wikipedia.org/wiki/Blog
https://br.wikipedia.org/wiki/Blog
https://ca.wikipedia.org/wiki/Blog
https://cs.wikipedia.org/wiki/Blog
https://cy.wikipedia.org/wiki/Blog
https://da.wikipedia.org/wiki/Blog
https://de.wikipedia.org/wiki/Blog
https://et.wikipedia.org/wiki/Ajaveeb
https://el.wikipedia.org/wiki/%CE%99%CF%83%CF%84%CE%BF%CE%BB%CF%8C%CE%B3%CE%B9%CE%BF
https://es.wikipedia.org/wiki/Blog
https://eo.wikipedia.org/wiki/Blogo
https://eu.wikipedia.org/wiki/Blog
https://fa.wikipedia.org/wiki/%D9%88%D8%A8%D9%84%D8%A7%DA%AF
https://fo.wikipedia.org/wiki/Bloggur
https://fr.wikipedia.org/wiki/Blog
https://fy.wikipedia.org/wiki/Webloch
https://ga.wikipedia.org/wiki/Blag
https://gl.wikipedia.org/wiki/Blog
https://glk.wikipedia.org/wiki/%D9%88%D8%A8%D9%84%D8%A7%DA%AF
https://gu.wikipedia.org/wiki/%E0%AA%AC%E0%AB%8D%E0%AA%B2%E0%AB%89%E0%AA%97
https://ko.wikipedia.org/wiki/%EB%B8%94%EB%A1%9C%EA%B7%B8
https://hy.wikipedia.org/wiki/%D4%B2%D5%AC%D5%B8%D5%A3
https://hi.wikipedia.org/wiki/%E0%A4%9A%E0%A4%BF%E0%A4%9F%E0%A5%8D%E0%A4%A0%E0%A4%BE
https://hr.wikipedia.org/wiki/Mre%C5%BEni_dnevnik
https://io.wikipedia.org/wiki/Blogo
https://ilo.wikipedia.org/wiki/Blog
https://id.wikipedia.org/wiki/Blog
https://ia.wikipedia.org/wiki/Blog
https://ie.wikipedia.org/wiki/Blog
https://os.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%B3
https://is.wikipedia.org/wiki/Blogg
https://it.wikipedia.org/wiki/Blog
https://he.wikipedia.org/wiki/%D7%91%D7%9C%D7%95%D7%92
https://jv.wikipedia.org/wiki/Blog
https://kn.wikipedia.org/wiki/%E0%B2%AC%E0%B3%8D%E0%B2%B2%E0%B2%BE%E0%B2%97%E0%B3%8D
https://ka.wikipedia.org/wiki/%E1%83%91%E1%83%9A%E1%83%9D%E1%83%92%E1%83%98
https://kk.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%B3
https://sw.wikipedia.org/wiki/Blogu
https://ku.wikipedia.org/wiki/Blog
https://lo.wikipedia.org/wiki/%E0%BA%9A%E0%BA%A5%E0%BA%B1%E0%BA%AD%E0%BA%81
https://la.wikipedia.org/wiki/Blog
https://lv.wikipedia.org/wiki/T%C4%ABmek%C4%BCa_%C5%BEurn%C4%81ls
https://lb.wikipedia.org/wiki/Blog
https://lt.wikipedia.org/wiki/Tinklara%C5%A1tis
https://lmo.wikipedia.org/wiki/Blog
https://hu.wikipedia.org/wiki/Blog
https://mk.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%B3
https://mg.wikipedia.org/wiki/Blaogy
https://ml.wikipedia.org/wiki/%E0%B4%AC%E0%B5%8D%E0%B4%B2%E0%B5%8B%E0%B4%97%E0%B5%8D
https://mt.wikipedia.org/wiki/Blogg
https://mr.wikipedia.org/wiki/%E0%A4%85%E0%A4%A8%E0%A5%81%E0%A4%A6%E0%A4%BF%E0%A4%A8%E0%A5%80
https://xmf.wikipedia.org/wiki/%E1%83%91%E1%83%9A%E1%83%9D%E1%83%92%E1%83%98
https://ms.wikipedia.org/wiki/Blog
https://cdo.wikipedia.org/wiki/U%C5%8Dng-c%C3%A9
https://mwl.wikipedia.org/wiki/Blogue
https://mn.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%B3
https://nl.wikipedia.org/wiki/Blog
https://ne.wikipedia.org/wiki/%E0%A4%AC%E0%A5%8D%E0%A4%B2%E0%A4%97
https://ja.wikipedia.org/wiki/%E3%83%96%E3%83%AD%E3%82%B0
https://nqo.wikipedia.org/wiki/%DF%93%DF%91%DF%9F%DF%8F%DF%9C%DF%AD%DF%8D%DF%99
https://no.wikipedia.org/wiki/Blogg
https://nn.wikipedia.org/wiki/Blogg
https://oc.wikipedia.org/wiki/Bl%C3%B2g
https://mhr.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%B3%D0%B5%D1%80
https://uz.wikipedia.org/wiki/Blog
https://pa.wikipedia.org/wiki/%E0%A8%AC%E0%A8%B2%E0%A8%BE%E0%A8%97
https://km.wikipedia.org/wiki/%E1%9E%94%E1%9F%92%E1%9E%9B%E1%9E%BC%E1%9E%80
https://pl.wikipedia.org/wiki/Blog
https://pt.wikipedia.org/wiki/Blog
https://kaa.wikipedia.org/wiki/Blog
https://ro.wikipedia.org/wiki/Blog
https://ru.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%B3
https://sq.wikipedia.org/wiki/Ditari_Blog
https://scn.wikipedia.org/wiki/Blog
https://si.wikipedia.org/wiki/%E0%B7%80%E0%B7%92%E0%B6%BA%E0%B7%94%E0%B6%AB%E0%B7%94_%E0%B7%83%E0%B6%A7%E0%B7%84%E0%B6%B1%E0%B7%8A
https://simple.wikipedia.org/wiki/Blog
https://sk.wikipedia.org/wiki/Blog
https://sl.wikipedia.org/wiki/Blog
https://so.wikipedia.org/wiki/Buluug_(teknooloji)
https://ckb.wikipedia.org/wiki/%D8%A8%D9%84%DB%86%DA%AF
https://sr.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%B3
https://sh.wikipedia.org/wiki/Blog
https://su.wikipedia.org/wiki/Blog
https://fi.wikipedia.org/wiki/Blogi
https://sv.wikipedia.org/wiki/Blogg
https://tl.wikipedia.org/wiki/Blog
https://ta.wikipedia.org/wiki/%E0%AE%B5%E0%AE%B2%E0%AF%88%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AE%A4%E0%AE%BF%E0%AE%B5%E0%AF%81
https://tt.wikipedia.org/wiki/Blog
https://te.wikipedia.org/wiki/%E0%B0%AC%E0%B1%8D%E0%B0%B2%E0%B0%BE%E0%B0%97%E0%B1%81
https://tet.wikipedia.org/wiki/Blog
https://th.wikipedia.org/wiki/%E0%B8%9A%E0%B8%A5%E0%B9%87%E0%B8%AD%E0%B8%81
https://tg.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%B3
https://tr.wikipedia.org/wiki/Blog
https://tk.wikipedia.org/wiki/Blog
https://uk.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%B3
https://ur.wikipedia.org/wiki/%D8%A8%D9%84%D8%A7%DA%AF
https://vec.wikipedia.org/wiki/Blog
https://vi.wikipedia.org/wiki/Blog
https://wa.wikipedia.org/wiki/Waibe-blok
https://guc.wikipedia.org/wiki/Akalio%27ushaj%C3%BClee
https://zh-classical.wikipedia.org/wiki/%E7%B6%B2%E8%AA%8C
https://war.wikipedia.org/wiki/Blog
https://wuu.wikipedia.org/wiki/%E5%8D%9A%E5%AE%A2
https://yi.wikipedia.org/wiki/%D7%91%D7%9C%D7%90%D7%92
https://zh-yue.wikipedia.org/wiki/%E7%B6%B2%E8%AA%8C
https://zh.wikipedia.org/wiki/%E7%B6%B2%E8%AA%8C
https://dtp.wikipedia.org/wiki/Bolog
https://www.wikidata.org/wiki/Special:EntityPage/Q30849#sitelinks-wikipedia
/wiki/Blog
/wiki/Talk:Blog
/wiki/Blog
/w/index.php?title=Blog&action=edit
/w/index.php?title=Blog&action=history
/wiki/Blog
/w/index.php?title=Blog&action=edit
/w/index.php?title=Blog&action=history
/wiki/Special:WhatLinksHere/Blog
/wiki/Special:RecentChangesLinked/Blog
//en.wikipedia.org/wiki/Wikipedia:File_Upload_Wizard
/w/index.php?title=Blog&oldid=1284437113
/w/index.php?title=Blog&action=info
/w/index.php?title=Special:CiteThisPage&page=Blog&id=1284437113&wpFormIdentifier=titleform
/w/index.php?title=Special:UrlShortener&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FBlog
/w/index.php?title=Special:QrCode&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FBlog
/w/index.php?title=Special:DownloadAsPdf&page=Blog&action=show-download-screen
/w/index.php?title=Blog&printable=yes
https://commons.wikimedia.org/wiki/Category:Blogs
https://en.wikiquote.org/wiki/Blogging
https://en.wikiversity.org/wiki/Blogging
https://www.wikidata.org/wiki/Special:EntityPage/Q30849
/wiki/Wikipedia:Protection_policy#semi
/wiki/Blogger_(service)
/wiki/Blog_(disambiguation)
/wiki/Journalism
/wiki/File:Radio._CBC_Offices_BAnQ_P48S1P23108_(cropped).jpg
/wiki/News
/wiki/News_style
/wiki/Five_Ws
/wiki/Journalism_ethics_and_standards
/wiki/Code_of_ethics_in_media
/wiki/Journalism_culture
/wiki/Journalistic_objectivity
/wiki/News_values
/wiki/Source_(journalism)
/wiki/Defamation
/wiki/Sensationalism
/wiki/Editorial_independence
/wiki/Journalism_school
/wiki/Index_of_journalism_articles
/wiki/Arts_journalism
/wiki/Business_journalism
/wiki/Data_journalism
/wiki/Entertainment_journalism
/wiki/Environmental_journalism
/wiki/Fashion_journalism
/wiki/Local_news
/wiki/Medical_journalism
/wiki/Music_journalism
/wiki/Political_journalism
/wiki/Science_journalism
/wiki/Sports_journalism
/wiki/Technology_journalism
/wiki/Traffic_reporting
/wiki/Video_game_journalism
/wiki/War_correspondent
/wiki/Weather_forecasting
/wiki/World_news
/wiki/Adversarial_journalism
/wiki/Advocacy_journalism
/wiki/Journalistic_interventionism
/wiki/Analytic_journalism
None
/wiki/Broadcast_journalism
/wiki/Churnalism
/wiki/Citizen_journalism
/wiki/Civic_journalism
/wiki/Collaborative_journalism
/wiki/Comics_journalism
/wiki/Community_journalism
/wiki/Data_journalism
/wiki/Database_journalism
/wiki/Digital_journalism
/wiki/Explanatory_journalism
/wiki/Fact-checking
/wiki/Gonzo_journalism
/wiki/Human-interest_story
/wiki/Immersion_journalism
/wiki/Interpretive_journalism
/wiki/Investigative_journalism
/wiki/Multimedia_journalism
/wiki/Narrative_journalism
/wiki/New_Journalism
/wiki/Non-profit_journalism
/wiki/Opinion_journalism
/wiki/Peace_journalism
/wiki/Photojournalism
/wiki/Press_release
/wiki/Sensor_journalism
/wiki/Tabloid_journalism
/wiki/Underground_press
/wiki/Video_journalism
/wiki/Visual_journalism
/wiki/Watchdog_journalism
/wiki/Fake_news
/wiki/Fourth_Estate
/wiki/Fifth_Estate
/wiki/Freedom_of_the_press
/wiki/Infotainment
/wiki/Horse_race_journalism
/wiki/Media_bias
/wiki/False_balance
/wiki/News_desert
/wiki/Pink-slime_journalism
/wiki/Public_relations
/wiki/Propaganda_model
/wiki/Yellow_journalism
/wiki/News_media
/wiki/Newspaper
/wiki/Newspaper_of_record
/wiki/Magazine
/wiki/News_broadcasting
/wiki/Online_newspaper
/wiki/News_agency
/wiki/Alternative_media
/wiki/Journalist
/wiki/Columnist
None
/wiki/Editing
/wiki/Copy_editing
/wiki/Meteorologist
/wiki/News_presenter
/wiki/Photojournalism
/wiki/Pundit
/wiki/Portal:Journalism
/wiki/Category:Journalism
/wiki/Template:Journalism_sidebar
/wiki/Template_talk:Journalism_sidebar
/wiki/Special:EditPage/Template:Journalism_sidebar
/wiki/Internet
/wiki/File:Internet_map_1024_-_transparent,_inverted.png
/wiki/Opte_Project
/wiki/Routing
/wiki/Internet_access
/wiki/Internet_activism
/wiki/Internet_censorship
/wiki/Data_activism
/wiki/E-democracy
/wiki/Digital_divide
/wiki/Digital_rights
/wiki/Internet_freedom
/wiki/Freedom_of_information
/wiki/List_of_Internet_phenomena
/wiki/Net_neutrality
/wiki/Internet_privacy
/wiki/Right_to_Internet_access
/wiki/Slacktivism
/wiki/Sociology_of_the_Internet
/wiki/Global_Internet_usage
/wiki/Internet_vigilantism
/wiki/Virtual_community
/wiki/Virtual_volunteering
/wiki/Internet_governance
/wiki/Internet_Governance_Forum
/wiki/Regional_Internet_registry#Number_Resource_Organization
/wiki/Internet_Assigned_Numbers_Authority
/wiki/ICANN
/wiki/Internet_Engineering_Task_Force
/wiki/Internet_Society
/wiki/Information_infrastructure
/wiki/Domain_Name_System
/wiki/Hypertext_Transfer_Protocol
/wiki/Internet_exchange_point
/wiki/Internet_protocol_suite
/wiki/Internet_Protocol
/wiki/Transmission_Control_Protocol
/wiki/Internet_service_provider
/wiki/IP_address
/wiki/Internet_Message_Access_Protocol
/wiki/Simple_Mail_Transfer_Protocol
None
/wiki/Microblogging
/wiki/Email
/wiki/Internet_fax
/wiki/File_sharing
/wiki/File_transfer
/wiki/Online_game
/wiki/Instant_messaging
/wiki/Podcast
/wiki/Online_shopping
/wiki/Streaming_television
/wiki/Voice_over_IP
/wiki/World_Wide_Web
/wiki/Web_search_engine
/wiki/History_of_the_Internet
/wiki/List_of_the_oldest_currently_registered_Internet_domain_names
/wiki/List_of_Internet_pioneers
/wiki/Protocol_Wars
/wiki/Index_of_Internet-related_articles
/wiki/Outline_of_the_Internet
/wiki/File:Crystal_Clear_app_linneighborhood.svg
/wiki/Portal:Internet
/wiki/Template:Internet
/wiki/Template_talk:Internet
/wiki/Special:EditPage/Template:Internet
/wiki/Category:Internet_hosting
/wiki/Internet_hosting_service
/wiki/Virtual_private_server
/wiki/Dedicated_hosting_service
/wiki/Colocation_centre
/wiki/Cloud_computing
/wiki/Peer-to-peer_web_hosting
/wiki/Web_hosting_service
/wiki/Shared_web_hosting_service
/wiki/Clustered_web_hosting
None
/wiki/Blog_comment_hosting_service
/wiki/Guild_hosting_service
/wiki/Image_hosting_service
/wiki/Online_video_platform
/wiki/Wiki_hosting_service
/wiki/Application_service_provider
/wiki/Social_network_hosting_service
/wiki/File_hosting_service
/wiki/Image_hosting_service
/wiki/Online_video_platform
/wiki/Digital_music_store
/wiki/Remote_backup_service
/wiki/Game_server
/wiki/Home_server
/wiki/DNS_hosting_service
/wiki/Email_hosting_service
/wiki/Template:Internet_hosting
/wiki/Template_talk:Internet_hosting
/wiki/Special:EditPage/Template:Internet_hosting
/wiki/Clipping_(morphology)
#cite_note-1
/wiki/Website
/wiki/Reverse_chronology
/wiki/Web_page
/wiki/Author
/wiki/Editing
/wiki/Newspaper
/wiki/News_media
/wiki/Think_tank
/wiki/Advocacy_group
/wiki/Web_traffic
/wiki/Twitter
/wiki/Microblogging
/wiki/News_media
/wiki/HTML
/wiki/Computer_programming
/wiki/File_Transfer_Protocol
/wiki/Hacker
/wiki/Web_2.0
#cite_note-2
/wiki/Social_networking_service
#cite_note-3
/wiki/Internet_forum#Moderators
/wiki/Wordfilter
/wiki/Hate_speech
/wiki/Philosophy
/wiki/Religion
/wiki/Art
/wiki/Science
/wiki/Politics
/wiki/Sport
/wiki/Online_diary
/wiki/Online_advertising
/wiki/Digital_image
/wiki/Hyperlink
/wiki/Art_blog
/wiki/Photoblog
/wiki/Video_blog
/wiki/MP3_blog
/wiki/Podcast
/wiki/Edublog
/wiki/Microblogging
/wiki/Social_media
/wiki/Facebook
/wiki/Instagram
#cite_note-4
/wiki/History_of_blogging
/wiki/Online_diary
/wiki/File:Eastcampusfire_glog_crop.png
/wiki/Real-time_computing
/wiki/Wearable_computer
/wiki/Head-up_display
/wiki/Jorn_Barger
#cite_note-5
/w/index.php?title=Peter_Merholz&action=edit&redlink=1
#cite_note-6
#cite_note-7
#cite_note-8
/wiki/Evan_Williams_(Internet_entrepreneur)
/wiki/Pyra_Labs
/wiki/Blogger_(service)
#cite_note-9
/wiki/Usenet
/wiki/GEnie
/wiki/Byte_Information_Exchange
/wiki/CompuServe
/wiki/Electronic_mailing_list
#cite_note-10
/wiki/Bulletin_board_system
/wiki/Internet_forum
/wiki/Bulletin_board
/wiki/Wikipedia:Please_clarify
/wiki/Encyclop%C3%A6dia_Britannica
#cite_note-11
#cite_note-12
/w/index.php?title=Ranjit_Bhatnagar&action=edit&redlink=1
#cite_note-13
/wiki/Justin_Hall
#cite_note-14
/wiki/Business_to_consumer
/wiki/Ty_Inc
/wiki/Beanie_Babies
#cite_note-BeanieBabies-15
/wiki/Online_diary
/wiki/Justin_Hall
/wiki/Swarthmore_College
#cite_note-16
/wiki/Jerry_Pournelle
#cite_note-17
/wiki/Dave_Winer
#cite_note-18
#cite_note-19
#cite_note-20
/wiki/EyeTap
/wiki/Sousveillance
/wiki/Zine
/w/index.php?title=Torill_Mortensen&action=edit&redlink=1
/wiki/Jill_Walker_Rettberg
#cite_note-21
/wiki/Ty,_Inc.
/wiki/HTML
/wiki/FTP
#cite_note-BeanieBabies-15
/wiki/Blog_hosting_service
/wiki/Web_hosting_service
/wiki/Bruce_Ableson
/wiki/Open_Diary
/wiki/Brad_Fitzpatrick
/wiki/LiveJournal
#cite_note-22
/wiki/Blogger_(service)
#cite_note-23
/wiki/File:Talkingpointsmemo2.png
/wiki/Trent_Lott
/wiki/United_States_Senate_Majority_Leader
/wiki/Trent_Lott
#cite_note-massing_essay-24
/wiki/United_States_Senate
/wiki/Strom_Thurmond
/wiki/Racial_segregation
/wiki/1948_United_States_presidential_election
/wiki/Josh_Marshall
/wiki/Talking_Points_Memo
/wiki/Rathergate
/wiki/Dan_Rather
/wiki/60_Minutes
/wiki/Forgery
/wiki/Little_Green_Footballs
/wiki/Rustem_Adagamov
/wiki/Alexei_Navalny
/wiki/United_Russia
#cite_note-25
/wiki/The_Wall_Street_Journal
/wiki/Vladimir_Putin
#cite_note-26
/wiki/Political_consultant
/wiki/Howard_Dean
/wiki/Wesley_Clark
/wiki/Labour_Party_(UK)
/wiki/Member_of_Parliament_(United_Kingdom)
/wiki/Tom_Watson_(Labour_politician)
/wiki/Fortune_(magazine)
/wiki/Engadget
/wiki/Xeni_Jardin
/wiki/Benjamin_Trott
/wiki/Mena_Trott
/wiki/Jonathan_I._Schwartz
/wiki/Robert_Scoble
/wiki/Jason_Calacanis
#cite_note-27
#cite_note-Ynet-28
/wiki/David_Saranga
/wiki/Israeli_Ministry_of_Foreign_Affairs
/wiki/Web_2.0
/wiki/Video_blog
#cite_note-Ynet-28
/wiki/Political_blog
#cite_note-Ynet3-29
/wiki/Microblogging
/wiki/2008%E2%80%932009_Israel%E2%80%93Gaza_conflict
#cite_note-JP-30
/wiki/IsraelPolitik
#cite_note-NYTs-31
/wiki/Barack_Obama
#cite_note-32
/wiki/Orwell_Prize
/wiki/2000s
/wiki/Grassroots
/wiki/Political_activism
#cite_note-:0-33
/wiki/File:BlogActive.com_Screenshot_2004.jpg
/wiki/Blogosphere
/wiki/Microblogging
#cite_note-34
/wiki/Tumblr
/wiki/Sina_Weibo
/wiki/Not-for-profit_organization
/wiki/Intranet
/wiki/Corporate_blog
/wiki/Employee_engagement
/wiki/Esprit_de_corps
/wiki/Morale
/wiki/Public_relations
/wiki/Ghostwriter
/wiki/Planet_(software)
/wiki/Subdomain
/wiki/Domain_name
http://planet.gnome.org/
/wiki/Political_blog
/wiki/Health_blog
/wiki/Travel_literature
/wiki/Book_Blog
#cite_note-35
#cite_note-36
/wiki/Fashion_blog
/wiki/Edublog
/wiki/Niche_blogging
/wiki/Classical_music_blog
/wiki/Legal_blogs
/wiki/Dream_diary
/wiki/Tutorial
#cite_note-37
/wiki/Art_blog
/wiki/MP3_blog
/wiki/Homemaking
/wiki/List_of_family-and-homemaking_blogs
/wiki/Spam_blog
/wiki/Video_blog
/wiki/Linklog
/wiki/Sketchblog
/wiki/Photoblog
/wiki/Tumblelog
/wiki/Gopher_Protocol
/wiki/Phlog
/wiki/Mobile_device
/wiki/Personal_digital_assistant
/wiki/Moblog
#cite_note-38
/wiki/EyeTap
/wiki/Sousveillance
/wiki/Wikipedia:Citation_needed
/wiki/Reverse_blog
/wiki/Web_forum
/wiki/Wikipedia:Citation_needed
/wiki/File:Blogosphere_map.jpg
/wiki/Blogosphere
/wiki/Blogosphere
/wiki/Linkback
/wiki/Internet_marketing
#cite_note-39
/wiki/List_of_search_engines#Blog
/wiki/Bloglines
/wiki/BlogScope
/wiki/Technorati
/wiki/Online_communities
/wiki/Global_Voices_Online
#cite_note-40
/wiki/Banner_advertisement
/wiki/Fake_blog
#cite_note-41
#cite_note-42
/wiki/Blogdex
/wiki/MIT_Media_Lab
/wiki/Wikipedia:No_original_research
/wiki/Memetracker
/wiki/Tailrank.com
/wiki/Alexa_Internet
/wiki/Technorati
/wiki/Xu_Jinglei
#cite_note-Fickling-43
/wiki/Xinhua
#cite_note-44
/wiki/Wikipedia:NOTRS
/wiki/Boing_Boing
#cite_note-Fickling-43
https://en.wikipedia.org/w/index.php?title=Blog&action=edit
#cite_note-45
/wiki/Permalink
#cite_note-46
/wiki/Websites
/wiki/Medium_(website)
/wiki/Substack
/wiki/Paywalls
/wiki/Newsletters
/wiki/Open_source
/wiki/WordPress
/wiki/Static_site_generator
/wiki/Hugo_(software)
/wiki/Jekyll_(software)
/wiki/Citizen_journalism
/wiki/Mainstream_media
/wiki/Gatekeeper
/wiki/Wikipedia:Citation_needed
/wiki/Jonathan_Dube
/wiki/The_Charlotte_Observer
/wiki/Hurricane_Bonnie_(1998)
#cite_note-47
/wiki/Atrios
/wiki/Glenn_Reynolds
/wiki/Instapundit
/wiki/Markos_Moulitsas_Z%C3%BAniga
/wiki/Daily_Kos
/wiki/Alex_Steffen
/wiki/Worldchanging
/wiki/Ana_Marie_Cox
/wiki/Wonkette
/wiki/Nate_Silver
/wiki/FiveThirtyEight.com
/wiki/Ezra_Klein
/wiki/The_American_Prospect
/wiki/The_Washington_Post
/wiki/Hugh_Hewitt
/wiki/Surgeon_General_of_the_United_States
/wiki/Richard_Carmona
/wiki/WVOX#Notable_Past_Programming
/wiki/Medical_Reserve_Corps
#cite_note-48
#cite_note-49
/wiki/Minority_language
/wiki/Goidelic_language
/wiki/Salam_Pax
/wiki/Ellen_Simonetti
/wiki/Jessica_Cutler
/wiki/ScrappleFace
/wiki/Blook
#cite_note-50
/wiki/Lulu_Blooker_Prize
#cite_note-51
/wiki/Julie_Powell
/wiki/Julie_%26_Julia
/wiki/Consumer-generated_advertising

In [ ]:
div = soup.find('div', class_='my-class')
heading = soup.find('h1', id='main-title')

In [ ]:
print(div , heading)

None None

In [ ]:
items = soup.select('div.container > ul > li')
for item in items:
    print(item.text)

In [ ]:
url = "https://www.scrapethissite.com/pages/forms/"

In [ ]:
page = requests.get(url)

In [ ]:
soup = BeautifulSoup(page.text , 'html')

HTML TO PANDAS DF

In [ ]:
from bs4 import BeautifulSoup

import requests

In [ ]:
url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'
soup = BeautifulSoup(requests.get(url).text , 'html')

In [ ]:
table = soup.find_all('table')[0]
table

<table class="wikitable sortable">
<caption>
</caption>
<tbody><tr>
<th>Rank
</th>
<th>Name
</th>
<th>Industry
</th>
<th>Revenue <br/>(USD millions)
</th>
<th>Revenue growth
</th>
<th>Employees
</th>
<th>Headquarters
</th></tr>
<tr>
<td>1
</td>
<td><a href="/wiki/Walmart" title="Walmart">Walmart</a>
</td>
<td><a href="/wiki/Retail" title="Retail">Retail</a>
</td>
<td style="text-align:center;">648,125
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 6.0%
</td>
<td style="text-align:center;">2,100,000
</td>
<td><a href="/wiki/Bentonville,_Arkansas" title="Bentonville, Arkansas">Bentonville, Arkansas</a>
</td></tr>
<tr>
<td>2
</td>
<td><a href="/wiki/Amazon_(company)" title="Amazon (company)">Amazon</a>
</td>
<td>Retail and <a href="/wiki/Cloud_computing" title="Cloud computing">cloud computing</a>
</td>
<td style="text-align:center;">574,785
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.9%
</td>
<td style="text-align:center;">1,525,000
</td>
<td><a href="/wiki/Seattle" title="Seattle">Seattle, Washington</a>
</td></tr>
<tr>
<td>3
</td>
<td><a class="mw-redirect" href="/wiki/Apple_Inc" title="Apple Inc">Apple</a>
</td>
<td><a href="/wiki/Electronics_industry" title="Electronics industry">Electronics industry</a>
</td>
<td style="text-align:center;">383,482
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span> <span data-sort-value="2999450000000000000♠" style="display:none"></span> -2.8%
</td>
<td style="text-align:center;">161,000
</td>
<td><a href="/wiki/Cupertino,_California" title="Cupertino, California">Cupertino, California</a>
</td></tr>
<tr>
<td>4
</td>
<td><a href="/wiki/UnitedHealth_Group" title="UnitedHealth Group">UnitedHealth Group</a>
</td>
<td><a class="mw-redirect" href="/wiki/Healthcare" title="Healthcare">Healthcare</a>
</td>
<td style="text-align:center;">371,622
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 14.6%
</td>
<td style="text-align:center;">440,000
</td>
<td><a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a>
</td></tr>
<tr>
<td>5
</td>
<td><a href="/wiki/Berkshire_Hathaway" title="Berkshire Hathaway">Berkshire Hathaway</a>
</td>
<td><a href="/wiki/Conglomerate_(company)" title="Conglomerate (company)">Conglomerate</a>
</td>
<td style="text-align:center;">364,482
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 20.7%
</td>
<td style="text-align:center;">396,500
</td>
<td><a href="/wiki/Omaha,_Nebraska" title="Omaha, Nebraska">Omaha, Nebraska</a>
</td></tr>
<tr>
<td>6
</td>
<td><a href="/wiki/CVS_Health" title="CVS Health">CVS Health</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">357,776
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 10.9%
</td>
<td style="text-align:center;">259,500
</td>
<td><a href="/wiki/Woonsocket,_Rhode_Island" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a>
</td></tr>
<tr>
<td>7
</td>
<td><a href="/wiki/ExxonMobil" title="ExxonMobil">ExxonMobil</a>
</td>
<td><a href="/wiki/Petroleum_industry" title="Petroleum industry">Petroleum industry</a>
</td>
<td style="text-align:center;">344,582
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span> <span data-sort-value="2999450000000000000♠" style="display:none"></span> -16.7%
</td>
<td style="text-align:center;">61,500
</td>
<td><a href="/wiki/Spring,_Texas" title="Spring, Texas">Spring, Texas</a>
</td></tr>
<tr>
<td>8
</td>
<td><a class="mw-redirect" href="/wiki/Alphabet_Inc" title="Alphabet Inc">Alphabet</a>
</td>
<td><a href="/wiki/Technology" title="Technology">Technology</a> and cloud computing
</td>
<td style="text-align:center;">307,394
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 8.7%
</td>
<td style="text-align:center;">182,502
</td>
<td><a href="/wiki/Mountain_View,_California" title="Mountain View, California">Mountain View, California</a>
</td></tr>
<tr>
<td>9
</td>
<td><a href="/wiki/McKesson_Corporation" title="McKesson Corporation">McKesson Corporation</a>
</td>
<td>Health
</td>
<td style="text-align:center;">276,711
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 4.8%
</td>
<td style="text-align:center;">48,000
</td>
<td><a href="/wiki/Irving,_Texas" title="Irving, Texas">Irving, Texas</a>
</td></tr>
<tr>
<td>10
</td>
<td><a href="/wiki/Cencora" title="Cencora">Cencora</a>
</td>
<td><a href="/wiki/Pharmacy" title="Pharmacy">Pharmacy wholesale</a>
</td>
<td style="text-align:center;">262,173
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 9.9%
</td>
<td style="text-align:center;">44,000
</td>
<td><a href="/wiki/Conshohocken,_Pennsylvania" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a>
</td></tr>
<tr>
<td>11
</td>
<td><a href="/wiki/Costco" title="Costco">Costco</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">242,290
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 6.8%
</td>
<td style="text-align:center;">316,000
</td>
<td><a href="/wiki/Issaquah,_Washington" title="Issaquah, Washington">Issaquah, Washington</a>
</td></tr>
<tr>
<td>12
</td>
<td><a href="/wiki/JPMorgan_Chase" title="JPMorgan Chase">JPMorgan Chase</a>
</td>
<td><a href="/wiki/Financial_services" title="Financial services">Financial services</a>
</td>
<td style="text-align:center;">239,425
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 54.7%
</td>
<td style="text-align:center;">309,926
</td>
<td><a href="/wiki/New_York_City" title="New York City">New York City, New York</a>
</td></tr>
<tr>
<td>13
</td>
<td><a href="/wiki/Microsoft" title="Microsoft">Microsoft</a>
</td>
<td>Technology and cloud computing
</td>
<td style="text-align:center;">211,915
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 6.9%
</td>
<td style="text-align:center;">221,000
</td>
<td><a href="/wiki/Redmond,_Washington" title="Redmond, Washington">Redmond, Washington</a>
</td></tr>
<tr>
<td>14
</td>
<td><a href="/wiki/Cardinal_Health" title="Cardinal Health">Cardinal Health</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">205,012
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 13.0%
</td>
<td style="text-align:center;">47,520
</td>
<td><a href="/wiki/Dublin,_Ohio" title="Dublin, Ohio">Dublin, Ohio</a>
</td></tr>
<tr>
<td>15
</td>
<td><a href="/wiki/Chevron_Corporation" title="Chevron Corporation">Chevron Corporation</a>
</td>
<td>Petroleum industry
</td>
<td style="text-align:center;">200,949
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span> <span data-sort-value="2999450000000000000♠" style="display:none"></span> -18.4%
</td>
<td style="text-align:center;">45,600
</td>
<td><a class="mw-redirect" href="/wiki/Houston,_Texas" title="Houston, Texas">Houston, Texas</a>
</td></tr>
<tr>
<td>16
</td>
<td><a class="mw-redirect" href="/wiki/Cigna" title="Cigna">Cigna</a>
</td>
<td>Health insurance
</td>
<td style="text-align:center;">195,265
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 8.2%
</td>
<td style="text-align:center;">71,413
</td>
<td><a href="/wiki/Bloomfield,_Connecticut" title="Bloomfield, Connecticut">Bloomfield, Connecticut</a>
</td></tr>
<tr>
<td>17
</td>
<td><a href="/wiki/Ford_Motor_Company" title="Ford Motor Company">Ford Motor Company</a>
</td>
<td><a href="/wiki/Automotive_industry" title="Automotive industry">Automotive industry</a>
</td>
<td style="text-align:center;">176,191
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.5%
</td>
<td style="text-align:center;">177,000
</td>
<td><a href="/wiki/Dearborn,_Michigan" title="Dearborn, Michigan">Dearborn, Michigan</a>
</td></tr>
<tr>
<td>18
</td>
<td><a href="/wiki/Bank_of_America" title="Bank of America">Bank of America</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">171,912
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span><span data-sort-value="7000300000000000000♠" style="display:none"></span> 49.4%
</td>
<td style="text-align:center;">212,985
</td>
<td><a href="/wiki/Charlotte,_North_Carolina" title="Charlotte, North Carolina">Charlotte, North Carolina</a>
</td></tr>
<tr>
<td>19
</td>
<td><a href="/wiki/General_Motors" title="General Motors">General Motors</a>
</td>
<td>Automotive industry
</td>
<td style="text-align:center;">171,842
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 9.6%
</td>
<td style="text-align:center;">163,000
</td>
<td><a href="/wiki/Detroit" title="Detroit">Detroit, Michigan</a>
</td></tr>
<tr>
<td>20
</td>
<td><a class="mw-redirect" href="/wiki/Anthem_(company)" title="Anthem (company)">Elevance Health</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">171,340
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 9.4%
</td>
<td style="text-align:center;">104,900
</td>
<td><a href="/wiki/Indianapolis" title="Indianapolis">Indianapolis, Indiana</a>
</td></tr>
<tr>
<td>21
</td>
<td><a href="/wiki/Citigroup" title="Citigroup">Citigroup</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">156,820
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 55.1%
</td>
<td style="text-align:center;">237,925
</td>
<td><a href="/wiki/New_York_City" title="New York City">New York City, New York</a>
</td></tr>
<tr>
<td>22
</td>
<td><a class="mw-redirect" href="/wiki/Centene" title="Centene">Centene</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">153,999
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 6.5%
</td>
<td style="text-align:center;">67,700
</td>
<td><a href="/wiki/St._Louis" title="St. Louis">St. Louis, Missouri</a>
</td></tr>
<tr>
<td>23
</td>
<td><a class="mw-redirect" href="/wiki/The_Home_Depot" title="The Home Depot">The Home Depot</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">152,669
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span> <span data-sort-value="2999450000000000000♠" style="display:none"></span> -3.0%
</td>
<td style="text-align:center;">463,100
</td>
<td><a href="/wiki/Atlanta" title="Atlanta">Atlanta, Georgia</a>
</td></tr>
<tr>
<td>24
</td>
<td><a href="/wiki/Marathon_Petroleum" title="Marathon Petroleum">Marathon Petroleum</a>
</td>
<td>Petroleum industry
</td>
<td style="text-align:center;">150,307
</td>

In [ ]:
table_titles = table.find_all('th')
table_titles

[<th>Rank
 </th>,
 <th>Name
 </th>,
 <th>Industry
 </th>,
 <th>Revenue <br/>(USD millions)
 </th>,
 <th>Revenue growth
 </th>,
 <th>Employees
 </th>,
 <th>Headquarters
 </th>]

In [ ]:
table_titles = [table_title.text.strip() for table_title in table_titles]
table_titles

['Rank',
 'Name',
 'Industry',
 'Revenue (USD millions)',
 'Revenue growth',
 'Employees',
 'Headquarters']

In [ ]:
import pandas as pd
df = pd.DataFrame(columns = table_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD millions), Revenue growth, Employees, Headquarters]
Index: []

In [ ]:
 column_datas = table.find_all('tr')[1:]
 column_datas

[<tr>
 <td>1
 </td>
 <td><a href="/wiki/Walmart" title="Walmart">Walmart</a>
 </td>
 <td><a href="/wiki/Retail" title="Retail">Retail</a>
 </td>
 <td style="text-align:center;">648,125
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 6.0%
 </td>
 <td style="text-align:center;">2,100,000
 </td>
 <td><a href="/wiki/Bentonville,_Arkansas" title="Bentonville, Arkansas">Bentonville, Arkansas</a>
 </td></tr>,
 <tr>
 <td>2
 </td>
 <td><a href="/wiki/Amazon_(company)" title="Amazon (company)">Amazon</a>
 </td>
 <td>Retail and <a href="/wiki/Cloud_computing" title="Cloud computing">cloud computing</a>
 </td>
 <td style="text-align:center;">574,785
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.9%
 </td>
 <td style="text-align:center;">1,525,000
 </td>
 <td><a href="/wiki/Seattle" title="Seattle">Seattle, Washington</a>
 </td></tr>,
 <tr>
 <td>3
 </td>
 <td><a class="mw-redirect" href="/wiki/Apple_Inc" title="Apple Inc">Apple</a>
 </td>
 <td><a href="/wiki/Electronics_industry" title="Electronics industry">Electronics industry</a>
 </td>
 <td style="text-align:center;">383,482
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span> <span data-sort-value="2999450000000000000♠" style="display:none"></span> -2.8%
 </td>
 <td style="text-align:center;">161,000
 </td>
 <td><a href="/wiki/Cupertino,_California" title="Cupertino, California">Cupertino, California</a>
 </td></tr>,
 <tr>
 <td>4
 </td>
 <td><a href="/wiki/UnitedHealth_Group" title="UnitedHealth Group">UnitedHealth Group</a>
 </td>
 <td><a class="mw-redirect" href="/wiki/Healthcare" title="Healthcare">Healthcare</a>
 </td>
 <td style="text-align:center;">371,622
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 14.6%
 </td>
 <td style="text-align:center;">440,000
 </td>
 <td><a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a>
 </td></tr>,
 <tr>
 <td>5
 </td>
 <td><a href="/wiki/Berkshire_Hathaway" title="Berkshire Hathaway">Berkshire Hathaway</a>
 </td>
 <td><a href="/wiki/Conglomerate_(company)" title="Conglomerate (company)">Conglomerate</a>
 </td>
 <td style="text-align:center;">364,482
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 20.7%
 </td>
 <td style="text-align:center;">396,500
 </td>
 <td><a href="/wiki/Omaha,_Nebraska" title="Omaha, Nebraska">Omaha, Nebraska</a>
 </td></tr>,
 <tr>
 <td>6
 </td>
 <td><a href="/wiki/CVS_Health" title="CVS Health">CVS Health</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">357,776
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 10.9%
 </td>
 <td style="text-align:center;">259,500
 </td>
 <td><a href="/wiki/Woonsocket,_Rhode_Island" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a>
 </td></tr>,
 <tr>
 <td>7
 </td>
 <td><a href="/wiki/ExxonMobil" title="ExxonMobil">ExxonMobil</a>
 </td>
 <td><a href="/wiki/Petroleum_industry" title="Petroleum industry">Petroleum industry</a>
 </td>
 <td style="text-align:center;">344,582
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span> <span data-sort-value="2999450000000000000♠" style="display:none"></span> -16.7%
 </td>
 <td style="text-align:center;">61,500
 </td>
 <td><a href="/wiki/Spring,_Texas" title="Spring, Texas">Spring, Texas</a>
 </td></tr>,
 <tr>
 <td>8
 </td>
 <td><a class="mw-redirect" href="/wiki/Alphabet_Inc" title="Alphabet Inc">Alphabet</a>
 </td>
 <td><a href="/wiki/Technology" title="Technology">Technology</a> and cloud computing
 </td>
 <td style="text-align:center;">307,394
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 8.7%
 </td>
 <td style="text-align:center;">182,502
 </td>
 <td><a href="/wiki/Mountain_View,_California" title="Mountain View, California">Mountain View, California</a>
 </td></tr>,
 <tr>
 <td>9
 </td>
 <td><a href="/wiki/McKesson_Corporation" title="McKesson Corporation">McKesson Corporation</a>
 </td>
 <td>Health
 </td>
 <td style="text-align:center;">276,711
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 4.8%
 </td>
 <td style="text-align:center;">48,000
 </td>
 <td><a href="/wiki/Irving,_Texas" title="Irving, Texas">Irving, Texas</a>
 </td></tr>,
 <tr>
 <td>10
 </td>
 <td><a href="/wiki/Cencora" title="Cencora">Cencora</a>
 </td>
 <td><a href="/wiki/Pharmacy" title="Pharmacy">Pharmacy wholesale</a>
 </td>
 <td style="text-align:center;">262,173
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 9.9%
 </td>
 <td style="text-align:center;">44,000
 </td>
 <td><a href="/wiki/Conshohocken,_Pennsylvania" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a>
 </td></tr>,
 <tr>
 <td>11
 </td>
 <td><a href="/wiki/Costco" title="Costco">Costco</a>
 </td>
 <td>Retail
 </td>
 <td style="text-align:center;">242,290
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 6.8%
 </td>
 <td style="text-align:center;">316,000
 </td>
 <td><a href="/wiki/Issaquah,_Washington" title="Issaquah, Washington">Issaquah, Washington</a>
 </td></tr>,
 <tr>
 <td>12
 </td>
 <td><a href="/wiki/JPMorgan_Chase" title="JPMorgan Chase">JPMorgan Chase</a>
 </td>
 <td><a href="/wiki/Financial_services" title="Financial services">Financial services</a>
 </td>
 <td style="text-align:center;">239,425
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 54.7%
 </td>
 <td style="text-align:center;">309,926
 </td>
 <td><a href="/wiki/New_York_City" title="New York City">New York City, New York</a>
 </td></tr>,
 <tr>
 <td>13
 </td>
 <td><a href="/wiki/Microsoft" title="Microsoft">Microsoft</a>
 </td>
 <td>Technology and cloud computing
 </td>
 <td style="text-align:center;">211,915
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 6.9%
 </td>
 <td style="text-align:center;">221,000
 </td>
 <td><a href="/wiki/Redmond,_Washington" title="Redmond, Washington">Redmond, Washington</a>
 </td></tr>,
 <tr>
 <td>14
 </td>
 <td><a href="/wiki/Cardinal_Health" title="Cardinal Health">Cardinal Health</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">205,012
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 13.0%
 </td>
 <td style="text-align:center;">47,520
 </td>
 <td><a href="/wiki/Dublin,_Ohio" title="Dublin, Ohio">Dublin, Ohio</a>
 </td></tr>,
 <tr>
 <td>15
 </td>
 <td><a href="/wiki/Chevron_Corporation" title="Chevron Corporation">Chevron Corporation</a>
 </td>
 <td>Petroleum industry
 </td>
 <td style="text-align:center;">200,949
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span> <span data-sort-value="2999450000000000000♠" style="display:none"></span> -18.4%
 </td>
 <td style="text-align:center;">45,600
 </td>
 <td><a class="mw-redirect" href="/wiki/Houston,_Texas" title="Houston, Texas">Houston, Texas</a>
 </td></tr>,
 <tr>
 <td>16
 </td>
 <td><a class="mw-redirect" href="/wiki/Cigna" title="Cigna">Cigna</a>
 </td>
 <td>Health insurance
 </td>
 <td style="text-align:center;">195,265
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 8.2%
 </td>
 <td style="text-align:center;">71,413
 </td>
 <td><a href="/wiki/Bloomfield,_Connecticut" title="Bloomfield, Connecticut">Bloomfield, Connecticut</a>
 </td></tr>,
 <tr>
 <td>17
 </td>
 <td><a href="/wiki/Ford_Motor_Company" title="Ford Motor Company">Ford Motor Company</a>
 </td>
 <td><a href="/wiki/Automotive_industry" title="Automotive industry">Automotive industry</a>
 </td>
 <td style="text-align:center;">176,191
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.5%
 </td>
 <td style="text-align:center;">177,000
 </td>
 <td><a href="/wiki/Dearborn,_Michigan" title="Dearborn, Michigan">Dearborn, Michigan</a>
 </td></tr>,
 <tr>
 <td>18
 </td>
 <td><a href="/wiki/Bank_of_America" title="Bank of America">Bank of America</a>
 </td>
 <td>Financials
 </td>
 <td style="text-align:center;">171,912
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span><span data-sort-value="7000300000000000000♠" style="display:none"></span> 49.4%
 </td>
 <td style="text-align:center;">212,985
 </td>
 <td><a href="/wiki/Charlotte,_North_Carolina" title="Charlotte, North Carolina">Charlotte, North Carolina</a>
 </td></tr>,
 <tr>
 <td>19
 </td>
 <td><a href="/wiki/General_Motors" title="General Motors">General Motors</a>
 </td>
 <td>Automotive industry
 </td>
 <td style="text-align:center;">171,842
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 9.6%
 </td>
 <td style="text-align:center;">163,000
 </td>
 <td><a href="/wiki/Detroit" title="Detroit">Detroit, Michigan</a>
 </td></tr>,
 <tr>
 <td>20
 </td>
 <td><a class="mw-redirect" href="/wiki/Anthem_(company)" title="Anthem (company)">Elevance Health</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">171,340
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 9.4%
 </td>
 <td style="text-align:center;">104,900
 </td>
 <td><a href="/wiki/Indianapolis" title="Indianapolis">Indianapolis, Indiana</a>
 </td></tr>,
 <tr>
 <td>21
 </td>
 <td><a href="/wiki/Citigroup" title="Citigroup">Citigroup</a>
 </td>
 <td>Financials
 </td>
 <td style="text-align:center;">156,820
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 55.1%
 </td>
 <td style="text-align:center;">237,925
 </td>
 <td><a href="/wiki/New_York_City" title="New York City">New York City, New York</a>
 </td></tr>,
 <tr>
 <td>22
 </td>
 <td><a class="mw-redirect" href="/wiki/Centene" title="Centene">Centene</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">153,999
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 6.5%
 </td>
 <td style="text-align:center;">67,700
 </td>
 <td><a href="/wiki/St._Louis" title="St. Louis">St. Louis, Missouri</a>
 </td></tr>,
 <tr>
 <td>23
 </td>
 <td><a class="mw-redirect" href="/wiki/The_Home_Depot" title="The Home Depot">The Home Depot</a>
 </td>
 <td>Retail
 </td>
 <td style="text-align:center;">152,669
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png 2x" width="11"/></span></span> <span data-sort-value="2999450000000000000♠" style="display:none"></span> -3.0%
 </td>
 <td style="text-align:center;">463,100
 </td>
 <td><a href="/wiki/Atlanta" title="Atlanta">Atlanta, Georgia</a>
 </td></tr>,
 <tr>
 <td>24
 </td>
 <td><a href="/wiki/Marathon_Petroleum" title="Marathon Petroleum">Marathon Petroleum</a>
 </td>
 <td>Petroleum industry
 </td>

In [ ]:
for column_data in column_datas:
  row_data = column_data.find_all('td')
  row_data = [rd.text.strip() for rd in row_data]
  length = len(df)
  df.loc[length] = row_data

In [ ]:
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"648,125",6.0%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"574,785",11.9%,"1,525,000","Seattle, Washington"
2,3,Apple,Electronics industry,"383,482",-2.8%,"161,000","Cupertino, California"
3,4,UnitedHealth Group,Healthcare,"371,622",14.6%,"440,000","Minnetonka, Minnesota"
4,5,Berkshire Hathaway,Conglomerate,"364,482",20.7%,"396,500","Omaha, Nebraska"
...,...,...,...,...,...,...,...
95,96,TIAA,Financials,"45,735",11.8%,"16,023","New York City, New York"
96,97,CHS,Agriculture cooperative,"45,590",-4.6%,"10,609","Inver Grove Heights, Minnesota"
97,98,Bristol-Myers Squibb,Pharmaceutical industry,"45,006",-2.5%,"34,100","New York City, New York"
98,99,Dow Chemical Company,Chemical industry,"44,622",-21.6%,"35,900","Midland, Michigan"
99,100,Best Buy,Retail,"43,452",-6.1%,"85,000","Richfield, Minnesota"

In [ ]:
df.to_csv('companies_revenue_usa.csv', index=False)

In [ ]:
from google.colab import files
files.download('companies_revenue_usa.csv')